embabel:
  models:
    default-llm: gpt-5-mini
    default-embedding-model: text-embedding-3-small
    llms:
      CHEAPEST: gpt-5-mini
      standard: gpt-5-mini
      best: gpt-5
    embedding-services:
      fast: text-embedding-3-small
      accurate: text-embedding-3-large

  agent:
    logging:
      personality: montypython
